### ISSUE TITLE
What versions of Fortran can be translated?

### ISSUE THREAD

**Issue by Beliavsky** [bin123apple/F2C-Translator#2]
F2c can translate Fortran 77 to C. What versions of Fortran (Fortran 77, 90, 95, 2003, 2008, 2018, 2023) is this project targeting for translation? Could you please add this information to the Readme? Thanks.

**Comment by bin123apple** [comment]
Currently this model is only trained by using the f90 code (Updated this information in the **Model** section). We will train it with more data later.
